#!/bin/bash

# install software packages

sudo apt install shellcheck

# install starship
curl -sS https://starship.rs/install.sh | sh

# Description: Link dotfiles to home directory

mkdir -p ~/.config

ln -sf ~/dotfiles/bashrc ~/.bashrc
ln -sf ~/dotfiles/vimrc ~/.vimrc
ln -sf ~/dotfiles/starship.toml ~/.config/starship.toml

echo "Dotfiles linked!"